spring:
  application:
    name: apollo-adminservice
  profiles:
    active: ${apollo_profile}
  datasource:
    url: jdbc:mysql://localhost:3306/apolloconfigdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: zxy631866324
    driver-class-name: com.mysql.jdbc.Driver

ctrip:
  appid: 100003172

server:
  port: 8090

logging:
  file: /opt/logs/100003172/apollo-adminservice.log
