spring:
  application:
    name: apollo-configservice
  profiles:
    active: ${apollo_profile}
  datasource:
    url: jdbc:mysql://localhost:3306/apolloconfigdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: zxy631866324

ctrip:
  appid: 100003171

server:
  port: 8080

logging:
  file: /opt/logs/100003171/apollo-configservice.log
